import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  documentationSidebars: [
    { type: 'autogenerated', dirName: '.' },
  ],
};

export default sidebars;
