name: Dart Reactive Transport

permissions:
  contents: read
  pages: write
  id-token: write

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      - name: Dart build
        run: dart pub get

      - name: Dart Test
        run: dart run test/test.dart
  documentation:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          cache: yarn
          cache-dependency-path: 'documentation/yarn.lock'
      - name: Install
        run: cd documentation && yarn install --frozen-lockfile --non-interactive
      - name: Build
        run: cd documentation && yarn build        
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload
        uses: actions/upload-pages-artifact@v2
        with:
          path: documentation/build
      - name: Deployment
        id: deployment
        uses: actions/deploy-pages@v2